### ISSUE TITLE
BG takes on the globe

### ISSUE THREAD

**Issue by rconde01** [boostorg/geometry#375]
I watched/read this talk from meeting c++ 2015...has there been any progress?

**Comment by awulkiew** [comment]
Yes, have a look at:
 - release notes (after Boost 1.60): http://www.boost.org/libs/geometry/doc/html/geometry/release_notes.html
 - pull requests (closed since Dec 2015 and open): https://github.com/boostorg/geometry/pulls?q=is%3Aopen+is%3Apr

In general most of the algorithms (relational and set operations, envelope, distance PtLike-Any, area) in spherical equatorial are supported (besides some combinations of geometries in distance, buffer, centroid) and we're working on the same for geographic CS, most of the work is finished. We plan to release it in Boost 1.64.

**Comment by rconde01** [comment]
Great news!
