### ISSUE TITLE
Reduce test suite when Travis is detected?

### ISSUE THREAD

**Issue by pdimov** [boostorg/geometry#452]
Would it be possible to run a reduced version of the test suite when Travis is detected? Perhaps something along the lines of

```
import os ;

build-project core ;
// other critical tests

if ! [ os.environ TRAVIS ]
{

build-project concepts ; 
// other less critical tests

}
```

The reason Travis matters, even though you don't use it at the moment, is that the superproject Travis runs the library tests when a library is updated, such as f.ex. here: https://travis-ci.org/boostorg/boost/builds/329477374

**Comment by awulkiew** [comment]
Right, running all of the tests take very long time. I'll implement some quick, general test and enable it for travis.

Btw, do I recall correctly that some mechanism was added to Boost's testing framework for this purpose? I.e. to distinguish between critical and extensive testing. Because if that was the case then I could also add support for it.

**Comment by pdimov** [comment]
The documentation currently says that you can define `minimal`, `full` and `extra` test suites, but nothing uses them at the moment. They were part of Rene's future plans, but he quit, so I doubt that anything will come of it.

**Comment by awulkiew** [comment]
Thanks. I'll make the change before the end of the week.

**Comment by awulkiew** [comment]
It seems to work as expected (https://travis-ci.org/boostorg/boost/builds/331059922), closing.
