### ISSUE TITLE
Problems performing boolean operations on polygons with shared edges

### ISSUE THREAD

**Issue by lukegluke** [boostorg/geometry#770]
Hi,

It's been quite a while, are the any news about fixing problems with boolean operations on polygons with shared edges?
https://svn.boost.org/trac10/ticket/12118
https://svn.boost.org/trac10/ticket/12125

Maybe it has been fixed already?

**Comment by barendgehrels** [comment]
Thanks for your message!

Ticket 12118 is fixed in the meantime, and I just closed it.
Ticket 12125 is fixed by removing rescaling, which is (still) not the default but it should be in 2021.

Therefore I assigned this issue to myself and will close it as soon as we change the default, it took much longer than expected but we're nearly there now.

**Comment by barendgehrels** [comment]
As above, fixed by removing rescaling, testcase is added, it will be released in (hopefully) 1.78
In the meantime you could define `BOOST_GEOMETRY_NO_ROBUSTNESS` 
Therefore closing this issue.
