### ISSUE TITLE
Intersection does not behave as expected

### ISSUE THREAD

**Issue by Zilleplus** [boostorg/geometry#930]
I created a square of width 10, and a flat triangle of height 1 that crosses the square. When calculating the intersection I get the whole plane above the triangle. I would expect to get small triangle back.

example code:

```
#include<iostream>
#include<boost/geometry.hpp>

using namespace boost::geometry;

int main(){
    using point = model::point<int, 2, cs::cartesian>;
    using poly = model::polygon<point>;

    poly r = {{{0,0}, {0,10}, {10,10}, {10,0},{0,0}}};
    poly cross = {{{-10,2},{5,3},{20,2},{-10,2}}};

    std::vector<poly> out;
    intersection(r, cross, out);

    for(auto x : out)
    {
        std::cout << wkt(x) << std::endl;
    }

}
```
compiler explorer link: https://compiler-explorer.com/z/GhfhTGz7q

Output: POLYGON((0 2,0 10,10 10,10 2,0 2))
I would expect to get POLYGON((0 2, 5 3, 10 2, 0 2))

**Comment by Zilleplus** [comment]
the never version 1.78.0 still contains this bug.

**Comment by barendgehrels** [comment]
Did you try already with the define `BOOST_GEOMETRY_NO_ROBUSTNESS`?

**Comment by Zilleplus** [comment]
@barendgehrels thank you for the advice I did not.  I just tried and unfortunately the result is exactly the same.

**Comment by Kissh12** [comment]
can I work on this?

**Comment by barendgehrels** [comment]
> can I work on this?

Yes, you can try. But it won't be easy...
I'll have a look myself next Wednesday.

**Comment by Kissh12** [comment]
> > can I work on this?
> 
> Yes, you can try. But it won't be easy... I'll have a look myself next Wednesday.

can I have some help over this as I am new to this

**Comment by barendgehrels** [comment]
> > > can I work on this?
> > 
> > 
> > Yes, you can try. But it won't be easy... I'll have a look myself next Wednesday.
> 
> can I have some help over this as I am new to this

I would suggest then to start with a simpler issue. This is one of the more complex things in the library.

The best starting point is the documentation for contributors.

**Comment by barendgehrels** [comment]
It's because of the integer coordinates, there are integer divisions (no rounding, no conversion to floating point). This causes the intersection point to casted to its lower value.

See this picture:

![image](https://user-images.githubusercontent.com/334849/150117914-1dbb0cc2-0cc8-4996-9567-fed3de3baadc.png)

On the left side both intersection points are collocated. On the right side, that doesn't happen just because the truncation works the other way round there (that line goes from top to bottom - on the left side it goes from bottom to top).

It's probably fixable if we don't keep the current behavior to do only integer calculations on integer coordinates. If we properly round it will be better - but if the triangle is even flatter, it will collapse to nothing.

Even with this info, the intersection points are collocated, it should not give that whole upper polygon as intersection - but that's a different thing, a cluster of two collocated intersection points is harder to solve.

**Comment by barendgehrels** [comment]
Version with rounding, which is probably correct for this input
![image](https://user-images.githubusercontent.com/334849/150118837-7d49fa2c-245f-4d09-922c-164fb69900b8.png)

@awulkiew you also worked on this, do you think we should change segment-segment intersection to use floating point calculation and then round (instead of integer division and (automatically) trunc?

**Comment by awulkiew** [comment]
@Zilleplus why are you using integer coordinates in this case where clearly the output of the operation cannot be represented properly with them?

@barendgehrels I haven't put much thought into it but it seems that either the operation returns correct output (whatever this means) or we clearly state that integral coordinates are not supported by the segments/linestrings/polygons intersection.

E.g. this case doesn't make sense to me. It would if there were not diagonal segments, squares, steps only. Would the algorithm return correct result if the blue polygon was a rectangle or if diagonal segments were made out of horizontal/vertical steps?

**Comment by barendgehrels** [comment]
Or, diving further into it, we can still keep integer division but round, using techniques like described here:
https://stackoverflow.com/questions/2422712/rounding-integer-division-instead-of-truncating
and then not the accepted solution (it gives weird results for negative numbers) but this one:
```
int divRoundClosest(const int n, const int d)
{
  return ((n < 0) ^ (d < 0)) ? ((n - d/2)/d) : ((n + d/2)/d);
}
```

**Comment by barendgehrels** [comment]
>

**Comment by barendgehrels** [comment]
> @barendgehrels I haven't put much thought into it but it seems that either the operation returns correct output (whatever this means) or we clearly state that integral coordinates are not supported by the segments/linestrings/polygons intersection.
> 

We've always supported integral coordinates so we can't state that. And we don't want to for a generic library. We've also long-time users using integer coordinates (for example Volker).
In general, if the integers are large it will all work fine. If coordinates are small like this, they more depend on rounding and it's actually feasible to provide this rounding (as in my previous comment, it works). It's actually quite weird, or plainly wrong, to truncate an intersection point of (9.99 9.99) to (9,9). Providing rounding will give better results - even though for integer coordinates it won't always be perfect

**Comment by barendgehrels** [comment]
_(the closing was a wrong button click)_

**Comment by Zilleplus** [comment]
@barendgehrels your solution is great for my use case, your effort is very much appreciated from my side.

@awulkiew I am working on an applicated that does some kind of integration over a grid, cutting out some piece of a polygon and calculating the volume inside of it. I'd love discuss it further, but not sure if this is the right place. Advice is always appreciated. So yea maybe I should use floating points, could be.
Missing a little bit of points due to rounding is not such a big deal, but sometimes you get this kind of behavior that really messes things up for me.

**Comment by barendgehrels** [comment]
> but this one:
> 
> ```
> int divRoundClosest(const int n, const int d)

> ```

Well, this one was wrong as well for negative numbers. The one stating that it was correct didn't behave well for 0 nominators. So it's an adaption now.

It's now in review, PR #972
